name: PhoenixBorder
main: me.phoenixcantfly.phoenixborder.Main
version: 0.0.1
description: cool border is v cool
api-version: 1.18
softdepend: [Multiverse]

commands:
    setbordercentre:
        usage: /<command> <x> <z>
        description: Sets Border Centre
    setborderradius:
        usage: /<command> <radius> <time>
        description: Sets Border Radius
    setborderfloorheight:
        usage: /<command> <y> <time>
        description: Sets Border Floor Height
    setborderceilingheight:
        usage: /<command> <y> <time>
        description: Sets Border Ceiling Height
    enableborder:
        usage: /<command>
        description: Enables Border
    disableborder:
        usage: /<command>
        description: Disables Border
    getworldname:
        usage: /<command>
        description: Gets World Name
    setborderrgb:
        usage: /<command> <r> <g> <b>
        description: Sets Particle RGB
    setborderparticlesize:
        usage: /<command> <size>
        description: Sets Particle Size
    setborderparticledistance:
        usage: /<command> <distance> <time>
        description: Sets Distance Between Particles
    setborderparticledistancevertical:
        usage: /<command> <distance> <time>
        description: Sets Distance Between Particles
    setborderworld:
        usage: /<command> <world-name>
        description: Sets which world the border is in
    setborderdamage:
        usage: /<command> <damage>
        description: Sets how much damage border does at 1.25s intervals
